package handlers

import (
	"context"
	"database/sql"
	_ "embed"
	"encoding/base64"
	"errors"
	"fmt"
	"html/template"
	"log/slog"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	qrcode "github.com/skip2/go-qrcode"

	"github.com/mauroneto/whatsmeow-api/internal/instance"
)

// adminCSS is the shared Tailwind stylesheet for every manager page
// (admin + login). Generated by the Tailwind CLI from
// internal/handlers/static/src.css (see api/Makefile `make css-build`).
// The source file `static/app.css` is gitignored; this embed pulls the
// generated output into the binary at compile time.
//
// Why embed + inline (vs serving as a separate `/static/app.css`): the
// admin tool has few concurrent users and the CSS is small (~16KB
// minified). Inlining keeps the request model as one HTML response and
// avoids an extra route/handler. If the CSS ever grows beyond ~50KB we
// can switch to a separate file served from a route.
//
//go:embed static/app.css
var adminCSS []byte

// chromeHeader is the shared <header> block (the green bar with nav).
// Each page template includes it via the chrome funcMap.
const chromeHeader = `
<header class="app-header">
  <h1><a href="/admin/">slimwhats</a></h1>
  <div class="nav">
    <a href="/admin/">Instances</a>
    <a href="/admin/audit">Audit</a>
    <a href="/swagger" target="_blank" rel="noopener noreferrer">Swagger</a>
    <form class="inline" method="POST" action="/admin/logout"><button class="btn secondary btn-sm">Logout</button></form>
  </div>
</header>
`

// chromeFunc is the FuncMap entry that wraps a page body in the full
// admin layout. Each page template calls it as {{chrome .Body}}.
//
// Why this approach (vs the old "adminLayout template + {{define "content"}}"
// pattern): Go's html/template shares the parse tree across templates
// that descend from the same parent, so multiple `{{define "content"}}`
// blocks all overwrite each other — only the last-defined one wins,
// which made every page render the audit page. Inlining the chrome
// via a FuncMap sidesteps the shared-tree issue entirely.
func chromeFunc(title string, body template.HTML) (template.HTML, error) {
	out := fmt.Sprintf(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>slimwhats — %s</title>
<style>%s</style>
</head>
<body>
%s
<main>%s</main>
</body>
</html>`, title, string(adminCSS), chromeHeader, string(body))
	return template.HTML(out), nil
}

// adminFuncs is the FuncMap shared by all admin page templates.
var adminFuncs = template.FuncMap{
	"chrome": chromeFunc,
}

// adminListTmpl is the home page (US-019). Calls {{chrome .Body "Title"}}
// to render the full page; the chrome func wraps the body in the
// shared layout.
//
// Column order is intentional: name + created (operator scans these
// first) → status → phone/jid → webhook (configured?) → last activity
// (which falls back to created_at for new instances so the column is
// never blank). Empty cells render as muted "—" for visual consistency.
var adminListTmpl = template.Must(
	template.New("list").Funcs(adminFuncs).Parse(`{{define "render"}}<div class="card">
  <div class="flex justify-between items-center">
    <h2>Instances</h2>
    <a class="btn" href="/admin/instances/new">+ New instance</a>
  </div>
  {{if .ActionResult}}<div class="{{.ActionResultClass}}">{{.ActionResult}}</div>{{end}}
  {{if .Instances}}
  <div class="card-grid">
    {{range .Instances}}
    <a class="card card-clickable" href="/admin/instances/{{.ID}}" data-instance-id="{{.ID}}">
      <div class="flex justify-between items-start gap-2">
        <h3>{{.Name}}</h3>
        <span class="badge {{.Status}}">{{.Status}}</span>
      </div>
      <div class="card-meta">
        <div><span class="key">Phone</span>{{if .Phone}}{{.Phone}}{{else}}<span class="muted">—</span>{{end}}</div>
        <div><span class="key">Webhook</span>{{if .WebhookConfigured}}<span title="{{.WebhookURL}}">✓</span>{{else}}<span class="muted">—</span>{{end}}</div>
        <div><span class="key">Last seen</span>{{if .LastSeen}}{{.LastSeen}}{{else}}{{.Created}}{{end}}</div>
        <div><span class="key">Created</span><span class="muted">{{.Created}}</span></div>
      </div>
      <span class="card-open">Open →</span>
    </a>
    {{end}}
  </div>
  {{else}}
  <p class="muted">No instances yet. <a href="/admin/instances/new">Create one</a>.</p>
  {{end}}
</div>{{end}}`),
)

// adminNewTmpl is the create form (US-020).
var adminNewTmpl = template.Must(
	template.New("new").Funcs(adminFuncs).Parse(`{{define "render"}}<div class="card max-w-[540px]">
  <h2>New instance</h2>
  {{if .Error}}<div class="error">{{.Error}}</div>{{end}}
  <form method="POST" action="/admin/instances/new">
    <label for="name">Name</label>
    <input id="name" name="name" required maxlength="64" placeholder="e.g. Sales BR">
    <label for="api_key">API key (optional, leave blank to auto-generate)</label>
    <input id="api_key" name="api_key" placeholder="sk_live_...">
    <div class="row mt-2">
      <button class="btn" type="submit">Create</button>
      <a class="btn secondary" href="/admin/">Cancel</a>
    </div>
  </form>
</div>{{end}}`),
)

// adminDetailTmpl is the per-instance page (US-021). Compact for v1.
var adminDetailTmpl = template.Must(
	template.New("detail").Funcs(adminFuncs).Parse(`{{define "render"}}<div class="card">
  <div class="flex justify-between items-center">
    <h2>{{.Instance.Name}}</h2>
    <div>
      <a class="btn secondary" href="/admin/">Back</a>
    </div>
  </div>
  <table>
    <tr><th>ID</th><td><code>{{.Instance.ID}}</code></td></tr>
    <tr><th>Status</th><td><span class="badge {{.Instance.Status}}">{{.Instance.Status}}</span></td></tr>
    <tr><th>Phone</th><td data-row="phone">{{.Instance.Phone}}</td></tr>
    <tr><th>JID</th><td data-row="jid">{{.Instance.JID}}</td></tr>
    <tr><th>LID</th><td data-row="lid">{{.Instance.LID}}</td></tr>
    <tr><th>API key set at</th><td data-row="api_set_at">{{.Instance.APISetAt}}</td></tr>
    <tr><th>Webhook</th><td>{{if .Instance.WebhookConfigured}}{{.Instance.WebhookURL}}{{else}}<span class="muted">not configured</span>{{end}}</td></tr>
    <tr><th>Connected at</th><td data-row="connected_at">{{.Instance.ConnectedAt}}</td></tr>
    <tr><th>Last seen</th><td data-row="last_seen">{{.Instance.LastSeenAt}}</td></tr>
  </table>
</div>

<div class="card">
  <h2>Lifecycle</h2>
  <form method="POST" action="/admin/instances/{{.Instance.ID}}" class="flex gap-2 flex-wrap">
    <button class="btn" name="action" value="connect"{{if not .Instance.CanConnect}} disabled title="Connect is only available when the instance is disconnected or logged out"{{end}}>Connect</button>
    <button class="btn secondary" name="action" value="disconnect"{{if not .Instance.CanDisconnect}} disabled title="Disconnect is only available when the instance is connected"{{end}}>Disconnect</button>
    <button class="btn secondary" name="action" value="reconnect"{{if not .Instance.CanReconnect}} disabled title="Reconnect is only available when the instance is paired (connected, disconnected, or logged out)"{{end}}>Reconnect</button>
  </form>
  {{if .ActionResult}}<div class="{{.ActionResultClass}}">{{.ActionResult}}</div>{{end}}
  {{if .QR}}
  <div class="mt-4 text-center">
    <h3 class="text-left">QR code</h3>
    <p class="muted text-left">Open WhatsApp → Linked Devices → Link a Device → scan this code. The QR rotates every 60s.</p>
    <img id="qr-img" src="{{.QR}}" alt="WhatsApp pairing QR code" class="inline-block border border-gray-300 p-2 bg-white rounded-md">
  </div>
  {{end}}
</div>

<div class="card">
  <h2>Webhook</h2>
  <form method="POST" action="/admin/instances/{{.Instance.ID}}/webhook">
    <label for="wh_url">URL</label>
    <input id="wh_url" name="url" placeholder="https://example.com/wh" value="{{.Instance.WebhookURL}}">
    <label>Current secret</label>
    {{if .Instance.WebhookSecret}}
    <div class="flex gap-2 items-center">
      <input id="whsec" type="password" value="{{.Instance.WebhookSecret}}" readonly class="flex-1 font-mono text-sm" onclick="this.select()">
      <button class="btn secondary" type="button" onclick="var i=document.getElementById('whsec');var b=document.getElementById('whsec-btn');if(i.type==='password'){i.type='text';b.textContent='Hide'}else{i.type='password';b.textContent='Show'}" id="whsec-btn">Show</button>
    </div>
    <label for="wh_secret" class="mt-3">New secret (optional)</label>
    <input id="wh_secret" name="secret" type="password" placeholder="leave blank to keep current">
    {{else}}
    <input id="wh_secret" name="secret" type="password" placeholder="any non-empty value">
    {{end}}
    <button class="btn" type="submit">Save</button>
  </form>
  <p class="muted mt-2">Sent as <code>X-Webhook-Secret</code> on every event. Empty the URL and the new-secret field to clear the config.</p>
</div>

<div class="card">
  <h2>API key</h2>
  {{if .Instance.APIKey}}
  <div class="flex gap-2 items-center">
    <input id="apikey" type="password" value="{{.Instance.APIKey}}" readonly class="flex-1 font-mono text-sm" onclick="this.select()">
    <button class="btn secondary" type="button" onclick="var i=document.getElementById('apikey');var b=document.getElementById('apikey-btn');if(i.type==='password'){i.type='text';b.textContent='Hide'}else{i.type='password';b.textContent='Show'}" id="apikey-btn">Show</button>
  </div>
  <p class="muted mt-2">Click the field to select all, or click <b>Show</b> to read it directly. Use <b>Rotate</b> below to generate a new key (the old one dies immediately).</p>
  {{else}}
  <p class="muted">No API key set yet. Click <b>Rotate</b> below to generate one.</p>
  {{end}}
  <form method="POST" action="/admin/instances/{{.Instance.ID}}/api-key/rotate" class="mt-4 flex gap-2 items-center">
    <button class="btn danger" type="submit" onclick="return confirm('Rotate API key? The old key stops working immediately.')">Rotate API key</button>
  </form>
  {{if .NewAPIKey}}
  <div class="ok mt-4 break-all">New key: <code>{{.NewAPIKey}}</code></div>
  {{end}}
</div>

<div class="card">
  <h2>Danger zone</h2>
  <form method="POST" action="/admin/instances/{{.Instance.ID}}/delete" class="flex gap-2 items-center">
    <button class="btn danger" type="submit" onclick="return confirm('Delete this instance? This is irreversible.')">Delete instance</button>
  </form>
</div>{{end}}`),
)

// adminAuditTmpl is the audit log page (US-030).
var adminAuditTmpl = template.Must(
	template.New("audit").Funcs(adminFuncs).Parse(`{{define "render"}}<div class="card">
  <h2>Audit log</h2>
  {{if .Entries}}
  <table>
    <thead><tr><th>Time</th><th>User</th><th>Action</th><th>Target</th><th>IP</th><th>UA</th></tr></thead>
    <tbody>
    {{range .Entries}}
      <tr>
        <td>{{.Timestamp}}</td>
        <td>{{.Username}}</td>
        <td><code>{{.Action}}</code></td>
        <td>{{if .TargetID}}<a href="/admin/instances/{{.TargetID}}">{{.TargetID}}</a>{{else}}<span class="muted">—</span>{{end}}</td>
        <td>{{.SourceIP}}</td>
        <td class="muted text-xs max-w-[200px] truncate">{{.UserAgent}}</td>
      </tr>
    {{end}}
    </tbody>
  </table>
  {{else}}
  <p class="muted">No actions logged yet.</p>
  {{end}}
</div>{{end}}`),
)

// renderAdmin is a tiny helper: execute the named "render" template
// against data, wrap it in the chrome via the FuncMap, and write to
// c.Writer. Returns true on success, false on a render error (which
// has already been written to the response).
func renderAdmin(tmpl *template.Template, title string, data any, c *gin.Context) bool {
	var buf strings.Builder
	if err := tmpl.ExecuteTemplate(&buf, "render", data); err != nil {
		c.String(http.StatusInternalServerError, "template render: %v", err)
		return false
	}
	c.Header("Content-Type", "text/html; charset=utf-8")
	// Run the chrome function with the rendered body.
	html, err := chromeFunc(title, template.HTML(buf.String()))
	if err != nil {
		c.String(http.StatusInternalServerError, "chrome: %v", err)
		return false
	}
	_, _ = c.Writer.Write([]byte(html))
	return true
}

// InstanceRow is the row in the home page table.
type InstanceRow struct {
	ID                string
	Name              string
	Status            string
	Phone             string
	WebhookConfigured bool
	WebhookURL        string
	LastSeen          string // empty if the instance has never connected
	Created           string
	CreatedAt         time.Time
}

// AdminListPage handles GET /admin/.
func AdminListPage(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		rows, err := db.Query(`SELECT id, name, status, phone, webhook_url, last_seen_at, created_at FROM instances ORDER BY created_at DESC LIMIT 100`)
		if err != nil {
			c.String(http.StatusInternalServerError, "load failed: %v", err)
			return
		}
		defer rows.Close()
		var list []InstanceRow
		for rows.Next() {
			var r InstanceRow
			var phone, wh sql.NullString
			var ls sql.NullTime
			if err := rows.Scan(&r.ID, &r.Name, &r.Status, &phone, &wh, &ls, &r.CreatedAt); err != nil {
				continue
			}
			if phone.Valid {
				r.Phone = phone.String
			}
			if wh.Valid {
				r.WebhookConfigured = true
				r.WebhookURL = wh.String
			}
			if ls.Valid {
				r.LastSeen = ls.Time.UTC().Format("2006-01-02 15:04")
			}
			// Note: r.LastSeen stays "" if the instance has never connected.
			// The list template falls back to r.Created in that case so the
			// column never shows a meaningless "—".
			r.Created = r.CreatedAt.UTC().Format("2006-01-02 15:04")
			list = append(list, r)
		}
		// Surface a status banner after destructive actions (e.g.
		// delete via the form-dispatcher) — the form POSTs to
		// /admin/instances/{id}/delete, the handler redirects to
		// /admin/?msg=...&msg_class=... and we render the same
		// div the detail page uses.
		renderAdmin(adminListTmpl, "Instances", gin.H{
			"Instances":         list,
			"ActionResult":      c.Query("msg"),
			"ActionResultClass": c.Query("msg_class"),
		}, c)
	}
}

// AdminNewPage handles GET /admin/instances/new.
func AdminNewPage() gin.HandlerFunc {
	return func(c *gin.Context) {
		renderAdmin(adminNewTmpl, "New instance", gin.H{
			"Error": c.Query("error"),
		}, c)
	}
}

// AdminNewSubmit handles POST /admin/instances/new (the form on the
// "New instance" page). Creates the instance via the store, then
// redirects to the detail page — the detail page renders the
// show/hide API-key field, so the operator sees the new key right
// there. On validation failure, redirects back to the form with
// ?error=... so the page re-renders with a red banner above the
// inputs (mirrors the form-dispatcher pattern from the lifecycle /
// api-key / delete handlers).
func AdminNewSubmit(store *instance.Store) gin.HandlerFunc {
	return func(c *gin.Context) {
		name := strings.TrimSpace(c.PostForm("name"))
		apiKey := strings.TrimSpace(c.PostForm("api_key"))
		if name == "" {
			c.Redirect(http.StatusFound, "/admin/instances/new?error=Name+is+required.")
			return
		}
		inst, plaintext, err := store.Create(instance.CreateInput{
			Name:   name,
			APIKey: apiKey,
		})
		if err != nil {
			if errors.Is(err, instance.ErrNameTaken) {
				c.Redirect(http.StatusFound, "/admin/instances/new?error=An+instance+with+this+name+already+exists.")
				return
			}
			c.Redirect(http.StatusFound, "/admin/instances/new?error="+url.QueryEscape(err.Error()))
			return
		}
		// Pass the freshly-generated key through the query string
		// so the detail page can show it in a one-time "your new
		// key" banner. The show/hide field on the detail page
		// also reads from the DB so the operator can copy it from
		// there too.
		c.Redirect(http.StatusFound,
			"/admin/instances/"+inst.ID+
				"?msg=Instance+created.&msg_class=ok&new_api_key="+url.QueryEscape(plaintext))
	}
}

// AdminDetailPage handles GET /admin/instances/{id}.
//
// For an unpaired instance (status == "created"), the handler auto-
// fetches a fresh QR code from whatsmeow and renders it as a base64-
// encoded PNG data URI — no external CDN, no JS, no extra round-trip.
// The user just refreshes the page (Cmd+R) to get a new QR.
func AdminDetailPage(db *sql.DB, mgr *instance.Manager) gin.HandlerFunc {
	return func(c *gin.Context) {
		id := c.Param("id")
		v, err := getInstanceView(db, id)
		if err != nil {
			c.String(http.StatusInternalServerError, "load failed: %v", err)
			return
		}
		if v == nil {
			c.String(http.StatusNotFound, "not found")
			return
		}
		// Format times
		if v.ConnectedAt != "" {
			t, _ := time.Parse("2006-01-02 15:04:05.999999-07:00", v.ConnectedAt)
			if !t.IsZero() {
				v.ConnectedAt = t.UTC().Format("2006-01-02 15:04 MST")
			}
		}
		if v.LastSeenAt != "" {
			t, _ := time.Parse("2006-01-02 15:04:05.999999-07:00", v.LastSeenAt)
			if !t.IsZero() {
				v.LastSeenAt = t.UTC().Format("2006-01-02 15:04 MST")
			}
		}
		if v.APISetAt != "" {
			t, _ := time.Parse("2006-01-02 15:04:05.999999-07:00", v.APISetAt)
			if !t.IsZero() {
				v.APISetAt = t.UTC().Format("2006-01-02 15:04 MST")
			}
		}
		_ = v.CreatedAt
		_ = v.UpdatedAt

		// Auto-fetch a fresh QR if the instance isn't paired yet.
		// Skip when already paired (the QR block hides itself via
		// {{if .QR}} in the template).
		//
		// IMPORTANT: we check the *client's* logged-in state, not the
		// DB status. The DB status can drift (e.g. a Disconnected event
		// fires during a network blip while the client is in the middle
		// of pairing and gets re-stuck in "connected, not logged in"
		// state). When that happens, the DB says "disconnected" but
		// the client is actively waiting for a QR scan — exactly the
		// state where the operator needs to see the QR. fetchQRPNG
		// itself is a no-op when the client is logged in, so this
		// safe to call whenever we don't have a positive signal that
		// the device is paired.
		var qrPNG template.URL
		cli := mgr.Get(id)
		if cli != nil && !cli.IsLoggedIn() {
			qrPNG = fetchQRPNG(mgr, id)
		}

		renderAdmin(adminDetailTmpl, v.Name, gin.H{
			"Instance":          v,
			"ActionResult":      c.Query("msg"),
			"ActionResultClass": c.Query("msg_class"),
			"QR":                qrPNG,
			"NewAPIKey":         c.Query("new_api_key"),
		}, c)
	}
}

// fetchQRPNG lazy-loads the whatsmeow client, pulls one QR payload,
// renders it as a PNG, and returns the data URI as a template.URL
// (which the html/template engine treats as already-safe, bypassing
// the URL-context auto-escape that would otherwise strip the
// "data:" scheme). Returns template.URL("") on failure.
//
// The 30s timeout is generous because whatsmeow's first QR can take
// a few seconds to come through (the client has to start its
// internal handshake). Subsequent refreshes are fast.
func fetchQRPNG(mgr *instance.Manager, instanceID string) template.URL {
	cli := mgr.Get(instanceID)
	if cli == nil || cli.IsLoggedIn() {
		return template.URL("") // missing or already paired; nothing to show
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	state := mgr.QRState(instanceID)
	raw, err := instance.GetLatestQR(ctx, state, cli)
	if err != nil || raw == "" {
		slog.Warn("fetchQRPNG: get latest QR failed", "id", instanceID, "err", err)
		return template.URL("")
	}
	// Render as 256x256 PNG, medium error-correction. Pure Go, no
	// external CDN; the PNG is base64-embedded in the HTML.
	png, err := qrcode.Encode(raw, qrcode.Medium, 256)
	if err != nil {
		slog.Warn("fetchQRPNG: qrcode.Encode failed", "err", err)
		return template.URL("")
	}
	return template.URL("data:image/png;base64," + base64.StdEncoding.EncodeToString(png))
}

// AdminAuditPage handles GET /admin/audit.
func AdminAuditPage(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		rows, err := db.Query(`SELECT timestamp, username, action, target_id, source_ip, user_agent FROM admin_actions ORDER BY timestamp DESC LIMIT 100`)
		if err != nil {
			c.String(http.StatusInternalServerError, "load failed: %v", err)
			return
		}
		defer rows.Close()
		type entry struct {
			Timestamp string
			Username  string
			Action    string
			TargetID  string
			SourceIP  string
			UserAgent string
		}
		var list []entry
		for rows.Next() {
			var e entry
			var tid, ua sql.NullString
			if err := rows.Scan(&e.Timestamp, &e.Username, &e.Action, &tid, &e.SourceIP, &ua); err != nil {
				continue
			}
			if tid.Valid {
				e.TargetID = tid.String
			}
			if ua.Valid {
				e.UserAgent = ua.String
			}
			list = append(list, e)
		}
		renderAdmin(adminAuditTmpl, "Audit log", gin.H{"Entries": list}, c)
	}
}

// getInstanceView is a small helper that loads a single instance by id.
func getInstanceView(db *sql.DB, id string) (*InstanceView, error) {
	row := db.QueryRow(`
		SELECT id, name, status, phone, jid, lid, webhook_url, webhook_secret,
		       connected_at, last_seen_at, api_key, api_key_set_at, created_at, updated_at
		FROM instances WHERE id = ?`, id)
	var v InstanceView
	var phone, jid, lid, wh, whsec sql.NullString
	var ca, ls, as sql.NullTime
	var apiKey sql.NullString
	if err := row.Scan(&v.ID, &v.Name, &v.Status, &phone, &jid, &lid, &wh, &whsec, &ca, &ls, &apiKey, &as, &v.CreatedAt, &v.UpdatedAt); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	if phone.Valid {
		v.Phone = phone.String
	}
	if jid.Valid {
		v.JID = jid.String
	}
	if lid.Valid {
		v.LID = lid.String
	}
	if wh.Valid {
		v.WebhookURL = wh.String
		v.WebhookConfigured = true
	}
	// Webhook secret is stored in plaintext (post 2026-07-29 drop-
	// encryption). Surface the value to the detail page so the
	// show/hide field can render it; the field starts masked
	// (type="password") and the user toggles visibility client-side.
	if whsec.Valid && whsec.String != "" {
		v.WebhookSecret = whsec.String
	}
	if ca.Valid {
		v.ConnectedAt = ca.Time.UTC().Format("2006-01-02 15:04:05.999999-07:00")
	}
	if ls.Valid {
		v.LastSeenAt = ls.Time.UTC().Format("2006-01-02 15:04:05.999999-07:00")
	}
	if as.Valid {
		v.APISetAt = as.Time.UTC().Format("2006-01-02 15:04:05.999999-07:00")
	}
	// API key is stored in plaintext (post 2026-07-29 drop-bcrypt).
	// Surface the full value to the detail page so the show/hide field
	// can render it; the field starts masked (type="password") and the
	// user toggles visibility client-side.
	if apiKey.Valid && apiKey.String != "" {
		v.APIKeyMasked = "••••••••" + last4(apiKey.String)
		v.APIKey = apiKey.String
	}
	// Compute which lifecycle actions are valid right now. The
	// matrix:
	//
	//   pairing       (unpaired, QR showing on the detail page)
	//                 no lifecycle button applies — the operator's
	//                 job here is to scan the QR. All three hidden.
	//   connected     (paired, websocket open)
	//                 connect=NO (already there), disconnect=YES,
	//                 reconnect=YES (force fresh socket if stuck)
	//   disconnected  (paired, websocket closed)
	//                 connect=YES (resume session), disconnect=NO
	//                 (already there), reconnect=YES (kick)
	//   logged_out    (session revoked by server — re-pair required
	//                 to recover; "connect" can't fix it but is
	//                 included for symmetry with disconnected and
	//                 so the operator gets a non-error button to
	//                 try; it will just fail in a visible way)
	//                 connect=YES, disconnect=NO, reconnect=YES
	//
	// The full matrix is centralised here so the detail template
	// stays declarative and the same logic could be reused by the
	// JSON API or a future "actions" endpoint.
	switch v.Status {
	case instance.StatusConnected:
		v.CanConnect = false
		v.CanDisconnect = true
		v.CanReconnect = true
	case instance.StatusDisconnected, instance.StatusLoggedOut:
		v.CanConnect = true
		v.CanDisconnect = false
		v.CanReconnect = true
	default:
		// StatusPairing and any future status: nothing to do here.
		// The detail page renders a fresh QR when applicable.
		v.CanConnect = false
		v.CanDisconnect = false
		v.CanReconnect = false
	}
	return &v, nil
}

// last4 returns the last 4 characters of s, or s itself if shorter.
// Used for the "sk_live_••••••••abcd" mask display.
func last4(s string) string {
	if len(s) <= 4 {
		return s
	}
	return s[len(s)-4:]
}
